version: 2
jobs:
  build:
    docker:
      - image: 'circleci/node:8'
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - 'v1-dependencies-{{ checksum "package.json" }}'
            - v1-dependencies-
      - run: 
          name: Install dependencies
          command: npm install
      - save_cache:
          paths:
            - node_modules
          key: 'v1-dependencies-{{ checksum "package.json" }}'
      - run: 'npm run test'
      - run:
          name: 'Build Project'
          command: 'npm run build'
      - run: 
          name: Deploy Master to Firebase 
          command: './node_modules/.bin/firebase deploy --token=$FIREBASE_TOKEN'